env:
    MANIFEST: https://github.com/DerpFest-AOSP/manifest.git -b 13 --depth=1
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/ij-israfil/local_manifest.git
    TARGET: derp 
    LUNCH_COMBO: derp_${DEVICE}-user
    OUTPUT: D*.zip
    #CLO: drivex1:derp
    #CLO_1: ENCRYPTED[!a58fc3c6199cc26bd840c8905e8ac41aac52f41609791f60db8cacba7889c523b70ebe2a6639e864f0d34715f0d1e3bc!]
    URI: https://sourceforge.net/projects/evox1/files/derp/ccache.tar.gz/download
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
